### ISSUE TITLE
maximize_window() command does not work with NeedleDriver

### ISSUE THREAD

**Issue by derek-charles** [jlane9/pytest-needle#18]
## Expected Behavior
When maximize_window() command is used, Browser is expected to stay in maximized state.

## Actual Behavior
Browser collapses into smaller window at the beginning of every pytest script. As a workaround, I must use maximize_window() at the beginning of every script. Also when headless chrome is under the control of NeedleDriver, any arguments to change the browser size does not work.  

## Steps to Reproduce the Problem

  1. Initialize Browser, 
  2. give maximize_window() command using NeedleDriver
  - Browser size will collapse at the beginning of every test.

## Specifications

  - Version: pytest-needle 3.11, selenium 3.141
  - Platform: Windows 7

**Comment by jlane9** [comment]
@derek-charles I would agree that this should be the default behaviour, however this not an issue with this library and is instead an issue with `pytest-selenium` (a dependency). `pytest-selenium` opens a new browser window each test and thus resets its window size state with each test. A few other folks, [including myself](https://github.com/pytest-dev/pytest-selenium/pull/100), have left comments suggesting changing this, but it looks like it'll continue to operate this way.

You could override the `selenium` fixture with one that's scope is set to `session`, like suggested [here](https://github.com/pytest-dev/pytest-selenium/issues/59#issuecomment-200338319). Remember though you'll also have to create an override for `needle` as well, since the two are tied.
